server:
  port: 8782

spring:
  application:
    name: reviews-honeybadger
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: test
    url: jdbc:mysql://rm-wz999n5pno5303q674o.mysql.rds.aliyuncs.com:${MYSQL_PORT:3306}/ghd_reviews_admin?useUnicode=true&characterEncoding=UTF8
    username: ghd_crm_demo
    password: zo=TH09json*a
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  stream:
    default-binder: rabbit
  rabbitmq:
    host: 120.77.217.112
    port: ${RABBIT_MQ_PORT:5672}
    username: admin
    password: 123admin456
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
    consul:
      enabled: true
      host: 120.77.217.112
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        register: true
        enabled: true
sample:
  zipkin:
    enabled: false

mybatis:
  basepackage: com.gehuida.reviews.honeybadger.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

swagger:
  enabled: true
  base-package: com.gehuida.reviews.honeybadger
  title: reviews-admin
  version: 2.0-SNAPSHOT
  description: honeybadger
  contact:
    name: admin

auth:
  serviceId: reviews-auth
  user:
    token-header: Authorization
  client:
    id: reviews-honeybadger
    secret: 123456
    token-header: x-client-token

redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: 120.77.217.112
  port: ${REDIS_PORT:6379}
  password:
  timeout: 2000
  sysName: reviews-honeybadger
  enable: true
  database: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.gehuida.reviews.honeybadger: DEBUG